/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps/web/public/models/classic-tee.glb --types --transform 
Files: apps/web/public/models/classic-tee.glb [10.94MB] > C:\Users\ahmed\Desktop\DesignAI\classic-tee-transformed.glb [687.73KB] (94%)
Author: Dreira091 (https://sketchfab.com/Dreira091)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-97d508268ed942ed89007023eede821b
Title: T-shirt
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/classic-tee-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.005']} position={[0, 1.374, -0.021]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/classic-tee-transformed.glb')
